version: '2.0'
services:


  importer:
    build:                         # on mac osx based host
      context: ./docker/
      dockerfile: Dockerfile
    container_name: nlh_importer
#    restart: always
    volumes:
      - $INPATH/:$IN:ro
      - $OUTPATH/:$OUT
      - ./log:$LOG
      - ./src/main/resources:/usr/verticles
    #depends_on:
    #  - solr
    #  - redis
    mem_limit: 13GB
    env_file:
      - .env
    environment:
      - DOMAIN=${DOMAIN}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_EXTERNAL_PORT=${REDIS_EXTERNAL_PORT}
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
      - ELASTICSEARCH_EXTERNAL_PORT=${ELASTICSEARCH_EXTERNAL_PORT}
      - SOLR_ADR=${SOLR_ADR}
      - SOLR_HOST=${SOLR_HOST}
      - SOLR_EXTERNAL_PORT=${SOLR_EXTERNAL_PORT}
      - JAVA_OPTS=-Xms512M -Xmx2G
      - JRUBY_OPTS=-J-Xms512M -J-Xmx2G
      - JVM_ARGS=-Xms512M -Xmx2G
      - MAGICK_MEMORY_LIMIT=32
      - MAGICK_MAP_LIMIT=32

 
  # https://hub.docker.com/_/elasticsearch/
#  elasticsearch:
#    image: elasticsearch:2.4.1
#    container_name: nlh-elasticsearch
#    restart: always
#    ports:
#      - "$ELASTICSEARCH_EXTERNAL_PORT:$ELASTICSEARCH_PORT"
#      - "9300:9300"
#    volumes:
#    #  - $STORAGE/solr/:/opt/solr/gdz/data/
#      #- /opt/solr/gdz/data/
#      #- /usr/share/elasticsearch/data/elasticsearch
#      - ./data:/usr/share/elasticsearch/data
#    mem_limit: 1GB
#    #user: $USER_UID
#    env_file:
#      - .env

  # https://hub.docker.com/_/solr/
  solr:
    build: docker/solr/
    #image: solr:6.2.0
    container_name: nlh-solr
    restart: always
    ports:
      - "$SOLR_EXTERNAL_PORT:$SOLR_PORT"
    volumes:
      - ./storage/solr/:/opt/solr/nlh/data/
    mem_limit: 2GB
    user: $USER_UID
    env_file:
      - .env
    environment:
      - JAVA_OPTS=-Xms512M -Xmx2G
      - SOLR_JAVA_MEM=-Xms512M -Xmx2G

  redis:
    #build: docker/redis/
    image: redis:alpine
    command: redis-server --appendonly yes
    container_name: nlh-redis
    restart: always
    ports:
      - "$REDIS_EXTERNAL_PORT:$REDIS_PORT"
    volumes:
      - ./storage/redis/:/data/
      #- $STORAGE/redis/:/data/
#    user: $USER_UID
    mem_limit: 3GB
    env_file:
      - .env
    environment:
      - JAVA_OPTS=-Xms256M -Xmx3G

#