version: '2.0'
services:

  importer_base:
    build:                         # on mac osx based host
      context: ./docker/
      dockerfile: Dockerfile
    user: "${myUID}"
    working_dir: /usr/verticles
    env_file:
      - .env


  importer_indexer:
    extends: importer_base
    command: ["exec vertx  run $VERTICLE_HOME/$INDEXER_VERTICLE"]
    restart: always
    volumes:
      - $INPATH/:$IN:ro
      - $OUTPATH/:$OUT
      - ./log:$LOG
      - ./src/main/resources:/usr/verticles
    depends_on:
      - solr
      - redis
      - importer_services
    mem_limit: 3GB
    environment:
      - JAVA_OPTS=-Xms512M -Xmx3G -Dvertx.options.blockedThreadCheckInterval=60000 -Dvertx.options.maxWorkerExecuteTime=3600000000000 -Dvertx.options.maxEventLoopExecuteTime=60000000000
      - JVM_ARGS=-Xms512M -Xmx3G -Dvertx.options.blockedThreadCheckInterval=60000 -Dvertx.options.maxWorkerExecuteTime=3600000000000 -Dvertx.options.maxEventLoopExecuteTime=60000000000
      - JRUBY_OPTS=-J-Xms512M -J-Xmx3G

  importer_services:
    extends: importer_base
    command: ["exec vertx run $VERTICLE_HOME/$SERVICE_VERTICLE"]
    restart: always
    volumes:
      - ./log:$LOG
      - ./src/main/resources:/usr/verticles
    ports:
      - "8080:8080"
    mem_limit: 1GB
    environment:
      - JAVA_OPTS=-Xms512M -Xmx1G -Dvertx.options.blockedThreadCheckInterval=60000 -Dvertx.options.maxWorkerExecuteTime=3600000000000 -Dvertx.options.maxEventLoopExecuteTime=60000000000
      - JVM_ARGS=-Xms512M -Xmx1G -Dvertx.options.blockedThreadCheckInterval=60000 -Dvertx.options.maxWorkerExecuteTime=3600000000000 -Dvertx.options.maxEventLoopExecuteTime=60000000000
      - JRUBY_OPTS=-J-Xms512M -J-Xmx1G


  importer_converter:
    extends: importer_base
    command: ["exec vertx run $VERTICLE_HOME/$CONVERTER_VERTICLE"]
    volumes:
      - $INPATH/:$IN:ro
      - $OUTPATH/:$OUT
      - ./log:$LOG
      - ./src/main/resources:/usr/verticles
    depends_on:
      - solr
      - redis
      - importer_services
    mem_limit: 3GB
    environment:
      - JAVA_OPTS=-Xms512M -Xmx3G -Dvertx.options.blockedThreadCheckInterval=60000 -Dvertx.options.maxWorkerExecuteTime=3600000000000 -Dvertx.options.maxEventLoopExecuteTime=60000000000
      - JVM_ARGS=-Xms512M -Xmx3G -Dvertx.options.blockedThreadCheckInterval=60000 -Dvertx.options.maxWorkerExecuteTime=3600000000000 -Dvertx.options.maxEventLoopExecuteTime=60000000000
      - JRUBY_OPTS=-J-Xms512M -J-Xmx3G
      - MAGICK_MEMORY_LIMIT=32
      - MAGICK_MAP_LIMIT=32



  # https://hub.docker.com/_/solr/
  solr:
    build: docker/solr/
    #image: solr:6.5.1
    container_name: mets_importer_solr
    restart: always
    ports:
      - "$SOLR_EXTERNAL_PORT:$SOLR_PORT"
    volumes:
      - ./data/solr/<solr_core>/data/:/opt/solr/server/solr/mycores/<solr_core>/data/
      - ./data/solr/<solr_core2>/data/:/opt/solr/server/solr/mycores/<solr_core2>/data/
    mem_limit: 2GB
    env_file:
      - .env
    environment:
      - JAVA_OPTS=-Xms512M -Xmx2G
      - SOLR_JAVA_MEM=-Xms512M -Xmx2G
      - JVM_ARGS=-Xms512M -Xmx2G
      - myUID=$myUID


  redis:
    image: redis:3.0
    command: redis-server --appendonly yes
    container_name: mets_importer_redis
    restart: always
    ports:
      - "$REDIS_EXTERNAL_PORT:$REDIS_PORT"
    volumes:
      - redisdata/:/data/
    mem_limit: 2GB
    env_file:
      - .env
    environment:
      - JAVA_OPTS=-Xms256M -Xmx2G


volumes:
  solrdata:
  redisdata:

