version: '2.0'
services:

  importer_base:
    build:                         # on mac osx based host
      context: ./docker/
      dockerfile: Dockerfile
    user: "${myUID}"
    working_dir: /usr/verticles

  importer_indexer:
    extends: importer_base
    command: ["exec vertx run $VERTICLE_HOME/$INDEXER_VERTICLE"]
    restart: always
    volumes:
      - $INPATH/:$IN:ro
      - $OUTPATH/:$OUT
      - ./log:$LOG
      - ./src/main/resources:/usr/verticles
    depends_on:
      - solr
      - redis
    mem_limit: 5GB
    memswap_limit: 10GB
    #environment:
    #  - JAVA_OPTS=$IMPORTER_JAVA_OPTS
    #  - JVM_ARGS=$IMPORTER_JVM_ARGS
    #  - JRUBY_OPTS=$IMPORTER_JRUBY_OPTS
    env_file:
      - ./.env
      - ./indexer.env

  importer_converter:
    extends: importer_base
    command: ["exec vertx run $VERTICLE_HOME/$CONVERTER_VERTICLE"]
    restart: always
    volumes:
      - $INPATH/:$IN:ro
      - $OUTPATH/:$OUT
      - ./log:$LOG
      - ./src/main/resources:/usr/verticles
    depends_on:
      - solr
      - redis
    mem_limit: 4GB
    #environment:
    #  - JAVA_OPTS=$CONVERTER_JAVA_OPTS
    #  - JVM_ARGS=$CONVERTER_JVM_ARGS
    #  - JRUBY_OPTS=$CONVERTER_JRUBY_OPTS
    #  - MAGICK_MEMORY_LIMIT=$CONVERTER_MAGICK_MEMORY_LIMIT
    #  - MAGICK_MAP_LIMIT=$CONVERTER_MAGICK_MAP_LIMIT
    env_file:
      - ./.env
      - ./converter.env

  importer_services:
    extends: importer_base
    command: ["exec vertx run $VERTICLE_HOME/$SERVICE_VERTICLE"]
    restart: always
    volumes:
      - ./log:$LOG
      - ./src/main/resources:/usr/verticles
    depends_on:
      - importer_indexer
      - importer_converter
    ports:
      - "$SERVICES_EXTERNAL_PORT:$SERVICES_SOLR_PORT"
    mem_limit: 1GB
    #environment:
    #  - JAVA_OPTS=$SERVICE_JAVA_OPTS
    #  - JVM_ARGS=$SERVICE_JVM_ARGS
    #  - JRUBY_OPTS=$SERVICE_JRUBY_OPTS
    env_file:
      - ./.env
      - ./services.env

  # https://hub.docker.com/_/solr/
  solr:
    build: docker/solr/
    #image: solr:6.5.1
    container_name: mets_importer_solr
    restart: always
    ports:
      - "$SOLR_EXTERNAL_PORT:$SOLR_PORT"
    volumes:
      # without two separate data containers, persisting the data level, the config (e.g.
      # schema.xml) would also be persisted and it could not be changes afterwards, because
      # the volume will be mounted at runtime and the mounted data (and config) would overwrite
      # the changed config
      - solrdata_core1:/opt/solr/server/solr/mycores/<solr_core>/data/
      - solrdata_core2:/opt/solr/server/solr/mycores/<solr_core2>/data/
    mem_limit: 5GB
    env_file:
      - ./.env
    environment:
      - SOLR_JAVA_MEM=$SOLR_JAVA_MEM


  redis:
    image: redis:3.0
    command: redis-server --appendonly yes
    container_name: mets_importer_redis
    restart: always
    ports:
      - "$REDIS_EXTERNAL_PORT:$REDIS_PORT"
    volumes:
      - redisdata/:/data/
    mem_limit: 3GB
    env_file:
      - ./.env
    environment:
      - JAVA_OPTS=$REDIS_JAVA_OPTS


volumes:
  solrdata_core1:
  solrdata_core2:
  redisdata:

