version: '2.0'
services:

  importer:
    build:                         # on mac osx based host
      context: ./docker/
      dockerfile: Dockerfile
    container_name: nlh_importer
#    restart: always
    volumes:
      - $INPATH/:$IN:ro
      - $OUTPATH/:$OUT
      - ./log:$LOG
      - ./src/main/resources:/usr/verticles
    #depends_on:
    #  - solr
    ports:
      - "8080:8080"
    mem_limit: 13GB
    env_file:
      - .env
    environment:
      - SOLR_ADR=${SOLR_ADR}
      - SOLR_HOST=${SOLR_HOST}
      - SOLR_EXTERNAL_PORT=${SOLR_EXTERNAL_PORT}
      - JAVA_OPTS=-Xms512M -Xmx2G
      - JRUBY_OPTS=-J-Xms512M -J-Xmx2G
      - JVM_ARGS=-Xms512M -Xmx2G
      - MAGICK_MEMORY_LIMIT=32
      - MAGICK_MAP_LIMIT=32

 
  # https://hub.docker.com/_/solr/
  solr:
    build: docker/solr/
    #image: solr:6.2.0
    container_name: nlh-solr
    restart: always
    ports:
      - "$SOLR_EXTERNAL_PORT:$SOLR_PORT"
    volumes:
      - ./storage/solr/:/opt/solr/nlh/data/
    mem_limit: 2GB
    user: $USER_UID
    env_file:
      - .env
    environment:
      - JAVA_OPTS=-Xms512M -Xmx2G
      - SOLR_JAVA_MEM=-Xms512M -Xmx2G

