version: '2.0'
services:

  importer:
    build:                         # on mac osx based host
      context: ./docker/
      dockerfile: Dockerfile
    container_name: nlh_importer
#    restart: always
    volumes:
      - $INPATH/:$IN:ro
      - $OUTPATH/:$OUT
      - ./log:$LOG
      - ./src/main/resources:/usr/verticles
    depends_on:
      - solr
      - redis
    ports:
      - "8080:8080"
    user: "${myUID}"
    mem_limit: 26GB
    env_file:
      - .env
    environment:
      - SOLR_ADR=${SOLR_ADR}
      - SOLR_HOST=${SOLR_HOST}
      - SOLR_EXTERNAL_PORT=${SOLR_EXTERNAL_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_EXTERNAL_PORT=${REDIS_EXTERNAL_PORT}
      - JAVA_OPTS=-Xms512M -Xmx26G -Dvertx.options.blockedThreadCheckInterval=60000 -Dvertx.options.maxWorkerExecuteTime=3600000000000 -Dvertx.options.maxEventLoopExecuteTime=60000000000
      - JVM_ARGS=-Xms512M -Xmx26G -Dvertx.options.blockedThreadCheckInterval=60000 -Dvertx.options.maxWorkerExecuteTime=3600000000000 -Dvertx.options.maxEventLoopExecuteTime=60000000000
      - JRUBY_OPTS=-J-Xms512M -J-Xmx26G
      - MAGICK_MEMORY_LIMIT=32
      - MAGICK_MAP_LIMIT=32


  # https://hub.docker.com/_/solr/
  solr:
    build: docker/solr/
    #image: solr:6.5.1
    container_name: nlh-solr
    restart: always
    ports:
      - "$SOLR_EXTERNAL_PORT:$SOLR_PORT"
    volumes:
      - solrdata/:/opt/solr/server/solr/mycores
    mem_limit: 3GB
    env_file:
      - .env
    environment:
      - JAVA_OPTS=-Xms512M -Xmx2G
      - SOLR_JAVA_MEM=-Xms512M -Xmx2G
      - myUID=$myUID
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - nlh

  redis:
    image: redis:3.0
    command: redis-server --appendonly yes
    container_name: mets_redis
    restart: always
    ports:
      - "$REDIS_EXTERNAL_PORT:$REDIS_PORT"
    volumes:
      - redisdata/:/data/
    mem_limit: 3GB
    env_file:
      - .env
    environment:
      - JAVA_OPTS=-Xms256M -Xmx3G



volumes:
  solrdata:
  redisdata: