FROM    solr:6.6.2
MAINTAINER  Jörg Panzer, SUB (based on https://github.com/docker-solr/docker-solr/blob/2e1ccd64970c65e7dacfe33203963b315f665cc3/5.5/Dockerfile)



ENV SOLR_SERVER_BASE    /opt/solr/server
ENV SOLR_BASE           /opt/solr/server/solr
ENV SOLR_GDZ_CORE           /opt/solr/server/solr/mycores/<solr_gdz_core>
ENV SOLR_GDZ_CORE2          /opt/solr/server/solr/mycores/<solr_gdz_core2>



COPY config/solr.in.sh /opt/solr/bin/solr.in.sh

USER root


COPY  config/sub/jetty.xml      $SOLR_SERVER_BASE/etc/jetty.xml


# core 1

RUN mkdir -p $SOLR_GDZ_CORE/data/

COPY  config/sub/currency.xml                           $SOLR_GDZ_CORE/conf/currency.xml
COPY  config/sub/mapping-FoldToASCII.txt                $SOLR_GDZ_CORE/conf/mapping-FoldToASCII.txt
COPY  config/sub/mapping-ISOLatin1Accent.txt            $SOLR_GDZ_CORE/conf/mapping-ISOLatin1Accent.txt
COPY  config/schema.xml                                 $SOLR_GDZ_CORE/conf/schema.xml
COPY  config/solrconfig.xml                             $SOLR_GDZ_CORE/conf/solrconfig.xml
COPY  config/stopwords.txt                              $SOLR_GDZ_CORE/conf/stopwords.txt
COPY  config/stopwords_en.txt                           $SOLR_GDZ_CORE/conf/stopwords_en.txt
COPY  config/synonyms.txt                               $SOLR_GDZ_CORE/conf/synonyms.txt
COPY  config/protwords.txt                              $SOLR_GDZ_CORE/conf/protwords.txt
COPY  config/elevate.xml                                $SOLR_GDZ_CORE/conf/elevate.xml
COPY  config/_rest_managed.json                         $SOLR_GDZ_CORE/conf/_rest_managed.json

COPY  config/_schema_analysis_stopwords_english.json    $SOLR_GDZ_CORE/conf/_schema_analysis_stopwords_english.json
COPY  config/_schema_analysis_synonyms_english.json     $SOLR_GDZ_CORE/conf/_schema_analysis_synonyms_english.json
COPY  config/admin-extra.menu-bottom.html               $SOLR_GDZ_CORE/conf/admin-extra.menu-bottom.html
COPY  config/admin-extra.menu-top.html                  $SOLR_GDZ_CORE/conf/admin-extra.menu-top.html
COPY  config/admin-extra.html                           $SOLR_GDZ_CORE/conf/admin-extra.html


# core 2

RUN mkdir -p $SOLR_GDZ_CORE2/data/

COPY  config/sub/currency.xml                           $SOLR_GDZ_CORE2/conf/currency.xml
COPY  config/sub/mapping-FoldToASCII.txt                $SOLR_GDZ_CORE2/conf/mapping-FoldToASCII.txt
COPY  config/sub/mapping-ISOLatin1Accent.txt            $SOLR_GDZ_CORE2/conf/mapping-ISOLatin1Accent.txt
COPY  config/schema2.xml                                 $SOLR_GDZ_CORE2/conf/schema.xml
COPY  config/solrconfig.xml                             $SOLR_GDZ_CORE2/conf/solrconfig.xml
COPY  config/stopwords.txt                              $SOLR_GDZ_CORE2/conf/stopwords.txt
COPY  config/stopwords_en.txt                           $SOLR_GDZ_CORE2/conf/stopwords_en.txt
COPY  config/synonyms.txt                               $SOLR_GDZ_CORE2/conf/synonyms.txt
COPY  config/protwords.txt                              $SOLR_GDZ_CORE2/conf/protwords.txt
COPY  config/elevate.xml                                $SOLR_GDZ_CORE2/conf/elevate.xml
COPY  config/_rest_managed.json                         $SOLR_GDZ_CORE2/conf/_rest_managed.json

COPY  config/_schema_analysis_stopwords_english.json    $SOLR_GDZ_CORE2/conf/_schema_analysis_stopwords_english.json
COPY  config/_schema_analysis_synonyms_english.json     $SOLR_GDZ_CORE2/conf/_schema_analysis_synonyms_english.json
COPY  config/admin-extra.menu-bottom.html               $SOLR_GDZ_CORE2/conf/admin-extra.menu-bottom.html
COPY  config/admin-extra.menu-top.html                  $SOLR_GDZ_CORE2/conf/admin-extra.menu-top.html
COPY  config/admin-extra.html                           $SOLR_GDZ_CORE2/conf/admin-extra.html


RUN chown -R $SOLR_USER:$SOLR_USER $SOLR_BASE

EXPOSE <solr_gdz_port>
WORKDIR /opt/solr
USER $SOLR_USER


CMD ["solr-foreground"]
