FROM vertx/vertx3:latest
#FROM vertx/vertx3-exec

ENV JRUBY_HOME /opt/jruby
ENV GEM_PATH /opt/jruby/lib/ruby/gems/shared/gems

ENV USER_UID=<UID>


RUN  useradd -r -u $USER_UID importer


ENV PATH $PATH:$JRUBY_HOME/bin

#RUN echo "ipv6" >> /etc/modules


RUN apt-get update \
    && apt-get install -y curl vim libc6-dev --no-install-recommends \
        imagemagick \
        ghostscript \
        pdftk \
    && rm -rf /var/lib/apt/lists/*



ENV JRUBY_VERSION 9.1.10.0
ENV JRUBY_SHA256 93ec6b55fa0d5b37e9f8131f76adc01efa82bebcef8df3e0de49e83dad3ee958

# lib conflict with jruby version: (TypeError) no implicit conversion of Java::OrgJruby::Ruby into String
#ENV JRUBY_VERSION 9.1.13.0
#ENV JRUBY_SHA256 9d156646623ac2f27174721035b52572a4b05690db7c1293295aa2c04aad3908

RUN mkdir /opt/jruby \
  && curl -fSL https://s3.amazonaws.com/jruby.org/downloads/${JRUBY_VERSION}/jruby-bin-${JRUBY_VERSION}.tar.gz -o /tmp/jruby.tar.gz \
  && echo "$JRUBY_SHA256 /tmp/jruby.tar.gz" | sha256sum -c - \
  && tar -zx --strip-components=1 -f /tmp/jruby.tar.gz -C /opt/jruby \
  && rm /tmp/jruby.tar.gz \
  && update-alternatives --install /usr/local/bin/ruby ruby /opt/jruby/bin/jruby 1
ENV PATH /opt/jruby/bin:$PATH


# skip installing gem documentation
RUN mkdir -p /opt/jruby/etc \
	&& { \
		echo 'install: --no-document'; \
		echo 'update: --no-document'; \
	} >> /opt/jruby/etc/gemrc


RUN gem install bundler


WORKDIR /

RUN mkdir -p <VERTICLE_HOME>
COPY Gemfile <VERTICLE_HOME>/Gemfile
COPY Gemfile.lock <VERTICLE_HOME>/Gemfile.lock

WORKDIR <VERTICLE_HOME>


RUN jruby -S bundle install

RUN chown -R importer <VERTICLE_HOME>

USER importer


WORKDIR <VERTICLE_HOME>
ENTRYPOINT ["sh", "-c"]


