source 'https://rubygems.org'

gem "addressable", ">= 2.8.0"

gem 'rsolr', '~> 2.0', '>= 2.0.2'
gem 'elasticsearch', '~> 2.0'

#gem 'redis', '~> 3.3', '>= 3.3.1'
gem 'redis', '~> 4.0', '>= 4.0.1'

gem 'json_pure', '~> 2.0', '>= 2.0.2'

gem 'logger', '~> 1.4', '>= 1.4.2'
gem 'gelf', '~> 3.1'

gem 'oai', '~> 0.4.0'
#gem 'oai_repository', '~> 0.9.0'
gem 'nokogiri', '~> 1.13'
gem 'orchard', '~> 0.2' # cdlib pairtree implementation


# gem 'fileutils', '~> 0.7'
#         or
# gem 'rubysl-fileutils', '~> 2.0', '>= 2.0.3'


# gem 'rmagick', '~> 2.16'
gem "mini_magick"

gem 'ruby-vips', '~> 2.0', '>= 2.0.7'

# pdf processing lib
#gem 'pdftk', '~> 0.0.4'

# pdf processing lib for disclaimer creation
#gem 'prawn', '~> 2.2', '>= 2.2.2'
gem 'prawn-svg', '~> 0.25.1'
gem 'ttfunk', '~> 1.5', '<= 1.5.1'

# Rest Client API
gem 'rest-client', '~> 2.0', '>= 2.0.2'

# S3 library
gem 'aws-sdk', '~> 3.0', '>= 3.0.1'

# Saxerator streaming xml-to-hash parser
gem 'saxerator', '~> 0.9.8'
