source 'https://rubygems.org'



gem 'rsolr', '~> 1.1', '>= 1.1.2'
gem 'elasticsearch', '~> 2.0'



#gem 'redis', '~> 3.3', '>= 3.3.1'
gem 'json_pure', '~> 2.0', '>= 2.0.2'
gem 'logger', '~> 1.2', '>= 1.2.8'

gem 'oai', '~> 0.4.0'
#gem 'oai_repository', '~> 0.9.0'
gem 'nokogiri', '~> 1.6', '>= 1.6.8'
gem 'orchard', '~> 0.2' # cdlib pairtree implementation