module Mappings


  STRCTYPE_MONTH_TO_NUMBER_HASH = {
      "JAN" => "01",
      "FEB" => "02",
      "MAR" => "03",
      "APR" => "04",
      "MAY" => "05",
      "JUN" => "06",
      "JUL" => "07",
      "AUG" => "08",
      "SEP" => "09",
      "OCT" => "10",
      "NOV" => "11",
      "DEC" => "12",
      "01"  => "01",
      "02"  => "02",
      "03"  => "03",
      "04"  => "04",
      "05"  => "05",
      "06"  => "06",
      "07"  => "07",
      "08"  => "08",
      "09"  => "09",
      "10"  => "10",
      "11"  => "11",
      "12"  => "12",
      "1"  => "01",
      "2"  => "02",
      "3"  => "03",
      "4"  => "04",
      "5"  => "05",
      "6"  => "06",
      "7"  => "07",
      "8"  => "08",
      "9"  => "09",
      "10"  => "10",
      "11"  => "11",
      "12"  => "12",
  }

  def Mappings.strctype_month_to_number(month)
    STRCTYPE_MONTH_TO_NUMBER_HASH[month.to_s]
  end

  STRCTYPE_NUMBER_TO_MONTH_HASH = {
      "01" => "Januar",
      "02" => "Februar",
      "03" => "März",
      "04" => "April",
      "05" => "Mai",
      "06" => "Juni",
      "07" => "Juli",
      "08" => "August",
      "09" => "September",
      "10" => "Oktober",
      "11" => "November",
      "12" => "Dezember",
      "1" => "Januar",
      "2" => "Februar",
      "3" => "März",
      "4" => "April",
      "5" => "Mai",
      "6" => "Juni",
      "7" => "Juli",
      "8" => "August",
      "9" => "September",
      "10" => "Oktober",
      "11" => "November",
      "12" => "Dezember",
      "JAN" => "Januar",
      "FEB" => "Februar",
      "MAR" => "März",
      "APR" => "April",
      "MAY" => "Mai",
      "JUN" => "Juni",
      "JUL" => "Juli",
      "AUG" => "August",
      "SEP" => "September",
      "OCT" => "Oktober",
      "NOV" => "November",
      "DEC" => "Dezember",
  }

  def Mappings.strctype_number_to_month(number)
    STRCTYPE_NUMBER_TO_MONTH_HASH[number.to_s]
  end

  STRCTYPE_LABEL_HASH = {
      "abstract" => "Abstrakt", # unused type
      "acknowledgment" => "Danksagung", # unused type
      "addendum" => "Addendum", # unused type
      "additional" => "Beilage", # unused type
      "advertising" => "Werbung", # unused type
      "annotation" => "Annotation", #
      "appendix" => "Appendix", # unused type
      "article" => "Artikel", #
      "attachedwork" => "Beigefügtes Werk", #
      "binding" => "Einband", #
      "bundle" => "Nachlass", #
      "chapter" => "Kapitel", #
      "contained_work" => "Enthaltenes Werk", #
      "contents" => "Inhaltsverzeichnis", #
      "corrigenda" => "Errata", #
      "cover" => "Einband", #
      "dedication" => "Widmung", #
      "epilogue" => "Epilogue", # unused type
      "errata" => "Errata", # unused type
      "figure" => "Abbildung", # unused type
      "file" => "Akte", #
      "folder" => "Mappe", #
      "headword" => "Stichwort", # unused type
      "illustration" => "Illustration", #
      "illustrationdescription" => "Bildbeschreibung", # unused type
      "index" => "Index", #
      "indexabbreviations" => "Abkürzungsverzeichnis", # unused type
      "indexauthor" => "Index of authors", # unused type
      "indexauthors" => "Autorenverzeichnis", # unused type
      "indexchronological" => "Chronologisches verzeichnis", # unused type
      "indexfigures" => "Abbildungsverzeichnis", # unused type
      "indexlocation" => "Ortsregister", # unused type
      "indexlocations" => "Ortsregister", # unused type
      "indexnames" => "Namensregister", # unused type
      "indexofchronology" => "Index (chronologisch)", # unused type
      "indexoverall" => "Gesamtindex", # unused type
      "indexpersons" => "Personenindex", # unused type
      "indexspecial" => "Spezialverzeichnis", # unused type
      "indexsubject" => "Fachbegriffsregister", # unused type
      "indextables" => "Tabellenverzeichnis", # unused type
      "indexvolume" => "Bandindex", # unused type
      "introduction" => "Einleitung", # unused type
      "issue" => "Heft", #
      "lang" => "Sprache|Sprachen", # unused type
      "legalcomment" => "Rechtskommentar", # unused type
      "legalnorm" => "Rechtsnorm", # unused type
      "letter" => "Brief", #
      "lettertoeditor" => "Brief an den Editor", # unused type
      "list" => "Liste", #
      "listofillustrations" => "Liste der Abbildungen", # unused type
      "listofmaps" => "Liste der Karten", # unused type
      "listofpublications" => "Publikationsverzeichnis", #
      "listoftables" => "Liste der Tabellen", #
      "map" => "Karte", #
      "message" => "Nachricht", # unused type
      "miscella" => "Miszelle", # unused type
      "miscelle" => "Miszelle", # unused type
      "monograph" => "Monograph", #
      "multivolume_work" => "Mehrbändiges Werk", #
      "multivolumework" => "Mehrbändiges Werk", #
      "music" => "Musik", # unused type
      "musical_notation" => "Noten", #
      "notes" => "Noten", # unused type
      "obituary" => "Nachruf", # unused type
      "other" => "Sonstiges", # unused type
      "otherdocstrct" => "Sonstiges", # unused type
      "partofwork" => "Teilwerk", # unused type
      "periodical" => "Zeitschrift", #
      "periodicalissue" => "Zeitschriftenheft", # unused type
      "periodicalpart" => "Zeitschriftenteil", # unused type
      "periodicalvolume" => "Zeitschriftenband", # unused type
      "photograph" => "Foto", #
      "poem" => "Gedicht", # unused type
      "preface" => "Vorwort", #
      "prepage" => "Deckblatt", # unused type
      "remarks" => "Anmerkungen", # unused type
      "review" => "Rezension", # unused type
      "section" => "Abschnitt", #
      "sheetmusic" => "Musik", # unused type
      "singlemap" => "Einzelne Karte", # unused type
      "supplement" => "Beilage", # unused type
      "table" => "Tabelle, Liste", #
      "tabledescription" => "Tabelle der Beschreibungen", # unused type
      "tablelist" => "Tabelle, Liste", # unused type
      "tableofabbreviations" => "Abkürzungsverzeichnis", # unused type
      "tableofcontents" => "Inhaltsverzeichnis", # unused type
      "tableofliteraturerefs" => "Literaturverzeichnis", # unused type
      "textsection" => "Textabschnitt", # unused type
      "theses" => "Dissertation", # unused type
      "title_page" => "Titelseite", #
      "titlepage" => "Titelseite", #
      "unit" => "Teil", # unused type
      "volume" => "Teil eines mehrbändigen Werkes", #
      "werk_beigefuegt" => "Beigefügtes Werk", # unused type
      "werk" => "Werk", # unused type
      "genre" => "Genre|Genres", #
      "announcement" => "Ankündigung", # unused type
      "beigefuegt" => "Beigefügt", # unused type
      "bibliography" => "Bibliographie", # unused type
      "collectivework" => "Sammelwerk", # unused type
      "comment" => "Kommentar", # unused type
      "courtdecision" => "Rechtsentscheidung", # unused type
      "curriculumvitae" => "Lebenslauf", # unused type
  }

  STRCTYPE_TYPE_HASH = {
      "abstract"       => "section",
      "acknowledgment" => "section",
      "addendum"       => "section",
      "additional"     => "additional", # DFGViewer datenset element not used in Goobi
      "advertising"                => "section",
      "announcement_advertisement" => "section",
      "announcement"               => "section",
      "announcementadvertisement"  => "section",
      "appendix"                   => "section",
      "article"                    => "article",
      "attached_work"              => "contained_work",
      "attachedwork"               => "contained_work",
      "bibliography"               => "section",
      "binding"                    => "binding",
      "bundle"                     => "bundle",
      "chapter"                    => "chapter",
      "colophon"                   => "colophon",
      "contained_work"             => "contained_work",
      "containedwork"              => "contained_work",
      "contents"                   => "contents",
      "corrigenda"                 => "corrigenda",
      "cover"                      => "cover",
      "curriculum_vitae"           => "section",
      "curriculumvitae"            => "section",
      "dedication_foreword_intro"  => "section",
      "dedication"                 => "dedication",
      "dedicationforewordintro"    => "section",
      "entry"                      => "section",
      "epilogue"                   => "section",
      "errata"                     => "corrigenda",
      "figure"                     => "illustration",
      "file"                       => "file",
      "folder"                     => "folder",
      "headword"                   => "section",
      "illustration_description"   => "illustration",
      "illustration"               => "illustration",
      "illustrationdescription"    => "illustration",
      "imprint_colophon"           => "colophon",
      "imprint"                    => "section",
      "imprintcolophon"            => "colophon",
      "index_author"               => "index",
      "index_location"             => "index",
      "index_overall"              => "index",
      "index_persons"              => "index",
      "index_special"              => "index",
      "index_subject"              => "index",
      "index"                      => "index",
      "indexauthor"                => "index",
      "indexlocation"              => "index",
      "indexoverall"               => "index",
      "indexpersons"               => "index",
      "indexspecial"               => "index",
      "indexsubject"               => "index",
      "introduction"               => "section",
      "issue"                      => "issue",
      "journal"                    => "periodical",
      "letter"                     => "letter",
      "list_of_publications"       => "section",
      "list"                       => "section",
      "listofpublications"         => "section",
      "manuscript"                 => "manuscript",
      "map"                        => "map",
      "message"                    => "section",
      "miscella"                   => "section",
      "miscellany"                 => "section",
      "multivolume_work"           => "multivolume_work",
      "multivolumework"            => "multivolume_work",
      "music"                      => "musical_notation",
      "musical_notation"           => "musical_notation",
      "musicalnotation"            => "musical_notation",
      "obituary"                   => "section",
      "other_doc_strct"            => "section",
      "other_doc_struct"           => "section",
      "other"                      => "section",
      "otherdocstrct"              => "section",
      "otherdocstruct"             => "section",
      "part_of_work"               => "section",
      "partofwork"                 => "section",
      "periodical_issue"           => "issue",
      "periodical_part"            => "section",
      "periodical_volume"          => "volume",
      "periodical"                 => "volume",
      #"periodical"                 => "periodical",
      "periodicalissue"          => "issue",
      "periodicalpart"           => "section",
      "periodicalvolume"         => "volume",
      "preface"                  => "preface",
      "prepage"                  => "section",
      "remarks"                  => "section",
      "review"                   => "section",
      "section"                  => "section",
      "sheet_music"              => "musical_notation",
      "sheetmusic"               => "musical_notation",
      "supplement"               => "section",
      "table_description"        => "table",
      "table_list"               => "section",
      "table_of_abbreviations"   => "table",
      "table_of_contents"        => "contents",
      "table_of_literature_refs" => "section",
      "table"                    => "table",
      "tabledescription"         => "table",
      "tablelist"                => "section",
      "tableofabbreviations"     => "table",
      "tableofcontents"          => "contents",
      "tableofliteraturerefs"    => "table",
      "text_section"             => "section",
      "textsection"              => "section",
      "theses"                   => "section",
      "title_page"               => "title_page",
      "title"                    => "title_page",
      "titlepage"                => "title_page",
      "unit"                     => "section",
      "verse"                    => "section",
      "volume"                   => "volume",
      "annotation"               => "annotation",
      "atlas"                    => "atlas",
      "manuscript"               => "manuscript",
      "monograph"                => "monograph",
      "photograph"               => "photograph",
      "research_paper"           => "section" # ,
      # "act" => "act",               # DFGViewer datenset element not used in Goobi
      # "address" => "address",               # DFGViewer datenset element not used in Goobi
      # "album" => "album",               # DFGViewer datenset element not used in Goobi
      # "bachelor_thesis" => "section",               # DFGViewer datenset element not used in Goobi
      # "bookplate" => "bookplate",               # DFGViewer datenset element not used in Goobi
      # "cartulary" => "cartulary",               # DFGViewer datenset element not used in Goobi
      # "collation" => "collation",               # DFGViewer datenset element not used in Goobi
      # "cover_back" => "cover",               # DFGViewer datenset element not used in Goobi
      # "cover_front" => "cover",               # DFGViewer datenset element not used in Goobi
      # "day" => "day",               # DFGViewer datenset element not used in Goobi
      # "diploma_thesis" => "section",               # DFGViewer datenset element not used in Goobi
      # "doctoral_thesis" => "section",               # DFGViewer datenset element not used in Goobi
      # "document" => "document",               # DFGViewer datenset element not used in Goobi
      # "dossier" => "dossier",               # DFGViewer datenset element not used in Goobi
      # "edge" => "edge",               # DFGViewer datenset element not used in Goobi
      # "endsheet" => "endsheet",               # DFGViewer datenset element not used in Goobi
      # "engraved_titlepage" => "engraved_titlepage",               # DFGViewer datenset element not used in Goobi
      # "engraved_titlepage" => "engraved_titlepage",               # DFGViewer datenset element not used in Goobi
      # "engravedtitlepage" => "engraved_titlepage",               # DFGViewer datenset element not used in Goobi
      # "fascicle" => "fascicle",               # DFGViewer datenset element not used in Goobi
      # "file" => "file",  # DFGViewer datenset element not used in Goobi
      # "fragment" => "fragment",               # DFGViewer datenset element not used in Goobi
      # "ground_plan"	=> "ground_plan",               # DFGViewer datenset element not used in Goobi
      # "habilitation_thesis" => "section",               # DFGViewer datenset element not used in Goobi
      # "image" => "image",               # DFGViewer datenset element not used in Goobi
      # "initial_decoration" => "initial_decoration",               # DFGViewer datenset element not used in Goobi
      # "judgement" => "judgement",               # DFGViewer datenset element not used in Goobi
      # "land_register" => "land_register",               # DFGViewer datenset element not used in Goobi
      # "leaflet" => "leaflet",               # DFGViewer datenset element not used in Goobi
      # "lecture" => "lecture",               # DFGViewer datenset element not used in Goobi
      # "magister_thesis" => "section",               # DFGViewer datenset element not used in Goobi
      # "master_thesis" => "section",               # DFGViewer datenset element not used in Goobi
      # "month" => "month",               # DFGViewer datenset element not used in Goobi
      # "newspaper" => "newspaper",               # DFGViewer datenset element not used in Goobi
      # "note" => "note",               # DFGViewer datenset element not used in Goobi
      # "official_notification" => "official_notification",               # DFGViewer datenset element not used in Goobi
      # "ornament" => "ornament",               # DFGViewer datenset element not used in Goobi
      # "paper" => "paper",               # DFGViewer datenset element not used in Goobi
      # "paste_down" => "paste_down",               # DFGViewer datenset element not used in Goobi
      # "plan" => "plan",               # DFGViewer datenset element not used in Goobi
      # "poster" => "poster",               # DFGViewer datenset element not used in Goobi
      # "preprint" => "preprint",               # DFGViewer datenset element not used in Goobi
      # "printed_archives" => "printed_archives",               # DFGViewer datenset element not used in Goobi
      # "printers_mark" => "printers_mark",               # DFGViewer datenset element not used in Goobi
      # "privileges" => "privileges",               # DFGViewer datenset element not used in Goobi
      # "proceeding" => "proceeding",               # DFGViewer datenset element not used in Goobi
      # "provenance" => "provenance",               # DFGViewer datenset element not used in Goobi
      # "register" => "register",  # DFGViewer datenset element not used in Goobi
      # "report" => "report",               # DFGViewer datenset element not used in Goobi
      # "scheme" => "scheme",               # DFGViewer datenset element not used in Goobi
      # "seal" => "seal",               # DFGViewer datenset element not used in Goobi
      # "spine" => "spine",               # DFGViewer datenset element not used in Goobi
      # "stamp" => "stamp",               # DFGViewer datenset element not used in Goobi
      # "study" => "study",               # DFGViewer datenset element not used in Goobi
      # "text" => "text",               # DFGViewer datenset element not used in Goobi
      # "year" => "year" # DFGViewer datenset element not used in Goobi
  }

  def Mappings.strctype_label(label)
    STRCTYPE_LABEL_HASH[label.downcase]
  end

  def Mappings.strctype_type(type)
    STRCTYPE_TYPE_HASH[type.downcase]
  end


  STRCTYPE_PRODUCT_SHORT_TO_LONG_NAME_HASH = {
      "nlh-eai1" => "Early American Imprints I / EAI I",
      "nlh-eai2" => "Early American Imprints II / EAI II",
      "nlh-ecj" => "Eighteenth Century Journals I & II / ECJ I & II",
      "nlh-emo" => "Empire Online / EMO",
      "nlh-moc" => "Macmillan Cabinet Papers / MOC",

      "nlh-tda1" => "The Times Digital Archive I / TDA I",
      "nlh-tda2" => "The Times Digital Archive I / TDA II",
      "nlh-tls" => "Times Literary Supplement Historical Archive / TLS",
      "nlh-ecc" => "The Economist: Historical Archive / ECON",
      #"nlh-eha" => "11",
      #"nlh-usc" => "12",
  }

  def Mappings.strctype_product_short_to_long_name(short_name)
    STRCTYPE_PRODUCT_SHORT_TO_LONG_NAME_HASH[short_name]
  end
end