class DisclaimerInfo
  attr_accessor :id,
                :log_id,
                :log_label_arr,
                :log_start_page_index_arr,
                :log_end_page_index_arr,
                :log_level_arr,
                :log_type_arr,
                :purl, :catalogue_arr,
                :title_arr,
                :subtitle_arr,
                :bycreator,
                :publisher,
                :place_publish,
                :year_publish_string,
                :genre_arr,
                :dc_arr,
                :subject_arr,
                :year_publisher,
                :shelfmark_arr,
                :rights_owner_arr,
                :parentdoc_work,
                :parentdoc_label,
                :parentdoc_type,
                :date,
                :product

end